# Generated by Django 2.0.3 on 2018-03-10 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido', models.CharField(max_length=200)),
                ('Direccion', models.CharField(max_length=10)),
                ('Telefono', models.CharField(max_length=10)),
                ('Email', models.CharField(max_length=10)),
                ('Consumidor_Final', models.BooleanField(default=True)),
                ('Empresa', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaIngreso', models.DateTimeField(auto_now=True)),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Marca', models.CharField(max_length=20)),
                ('Modelo', models.CharField(max_length=20)),
                ('Observacion', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='turno',
            name='Vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Vehiculo'),
        ),
    ]
