# Generated by Django 2.0.3 on 2018-03-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_auto_20180310_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='Patente',
            field=models.CharField(default=False, max_length=20),
            preserve_default=False,
        ),
    ]
